"""added outbox table

Revision ID: f49599da4022
Revises: d6a4cebc1bbc
Create Date: 2026-04-16 18:49:19.806752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f49599da4022"
down_revision: Union[str, Sequence[str], None] = "d6a4cebc1bbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
eventtypeenum = sa.Enum(
    "ORDER_CREATED",
    "ORDER_PAID",
    "ORDER_SHIPPED",
    "ORDER_CANCELLED",
    name="eventtypeenum",
    create_type=False,
)
outboxeventstatus = sa.Enum(
    "PENDING", "SENT", name="outboxeventstatus", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", eventtypeenum, nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", outboxeventstatus, server_default="PENDING", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "idempotency_key",
            sa.UUID(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_idempotency"),
    )
    op.create_index(
        "idx_outbox_pending",
        "outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_outbox_pending", table_name="outbox")
    op.drop_table("outbox")
    eventtypeenum.drop(op.get_bind(), checkfirst=True)
    outboxeventstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
