infrastructure:
  db:
    dsn: postgresql+asyncpg://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE_NAME}
    pool_size: 15
    pool_recycle: 1800
  clients:
    catalog_service:
      api_key: ${X_API_KEY}
      base_url: ${CATALOG_SERVICE_BASE_URL}
    payments_service:
      api_key: ${X_API_KEY}
      base_url: ${PAYMENTS_SERVICE_BASE_URL}
  hostname:
    service_name: ${SERVICE_NAME}
    namespace: ${NAMESPACE}
  kafka:
    producer:
      bootstrap_servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVERS:kafka:9092}
      topic: ${KAFKA_PRODUCER_TOPIC:student_system-order.events}
    consumer:
      bootstrap_servers: ${KAFKA_CONSUMER_BOOTSTRAP_SERVERS:kafka:9092}
      topic: ${KAFKA_CONSUMER_TOPIC:student_system-shipment.events}
      group_id: ${KAFKA_GROUP_ID:order-service-group}

    
